apiVersion: v1
kind: ConfigMap
metadata:
  name: qradar-syslog
data:
  syslog.conf: |
    module(load="imudp")
    input(type="imudp" port="514")
    action(
      type="omfwd"
      protocol="tcp"
      target="qradar.example.com"
      port="514"
      template="RSYSLOG_SyslogProtocol23Format"
    )
