apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "myapp.fullname" . }}-mongodb # Veya values.yaml'dan gelen bir isim
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: {{ .Values.mongodb.service.name | default "myapp-mongodb" }} # MongoDB servisin adı
  replicas: {{ .Values.mongodb.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      serviceAccountName: {{ include "myapp.serviceAccountName" . }}
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb # Bu isim mongodb-service.yaml'daki targetPort ile eşleşebilir
              containerPort: 27017 # MongoDB'nin dinlediği port
              protocol: TCP
          # Ortam değişkenleri (MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD vb. Secret'lardan alınmalı)
          # env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "myapp.fullname" . }}-mongodb-secret
          #       key: mongodb-root-username
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "myapp.fullname" . }}-mongodb-secret
          #       key: mongodb-root-password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db # MongoDB'nin veri yazdığı dizin
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes: # Bu bölüm doğrudan StatefulSet spec altında DEĞİL, template.spec.volumes altında olmalıydı.
               # StatefulSet'lerde volumeClaimTemplates kullanılır.
      # Bu kısım hatalı, aşağıdaki volumeClaimTemplates kullanılmalı
      {{- end }}
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: {{ .Values.mongodb.persistence.accessModes | default (list "ReadWriteOnce") | toYaml | nindent 12 }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
        {{- if .Values.mongodb.persistence.storageClass }}
        {{- if (eq "-" .Values.mongodb.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.mongodb.persistence.storageClass }}"
        {{- end }}
        {{- end }}
  {{- end }}