apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}  # values.yaml'daki service adıyla eşleşmeli
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb  # Deployment'taki container port adı
      protocol: TCP
      name: mongodb
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
