apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name | default (printf "%s-mongodb" (include "myapp.fullname" .)) }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mongodb.name }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb # Container port adı
      protocol: TCP
      name: mongodb
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mongodb.name }}