frontend:
  image:
    repository: meyfcsalik/frontend
    tag: latest

backend:
  image:
    repository: meyfcsalik/backend
    tag: latest

mongodb:
  image:
    repository: mongo
    tag: 6.0
  pvc:
    storage: 1Gi
