{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.service.name }}-pvc
  labels:
    {{- include "myapp.labels" . | nindent 8 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    {{- toYaml .Values.mongodb.persistence.accessModes | nindent 8 }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  {{- if (eq "-" .Values.mongodb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.mongodb.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
