apiVersion: v2
name: myapp
description: K3s CI/CD Projesi için Helm Chart
type: application

# Bu, chart'ın versiyonudur. CI/CD ile artırılabilir.
version: 0.1.0

# Bu, chart tarafından deploy edilecek uygulamanın versiyonudur.
appVersion: "1.0.0"
