apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-backend
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort | default "http" }} # containerPort adına veya sayısına referans
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}