# helm/my-app/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-frontend # Tam adı kullanalım
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend # Bu etiketi ekledik
spec:
  replicas: {{ .Values.frontend.replicaCount }} # replicaCount'u values'tan alalım
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend # Bu etiketi ekledik
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend # Bu etiketi ekledik
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            # Gerekliyse frontend için env değişkenleri buraya eklenir
            # - name: SOME_FRONTEND_VAR
            #   value: "value"
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts: # NGINX'in yazma iznine ihtiyaç duyduğu TÜM dizinler buraya eklendi
            - name: nginx-cache-volume
              mountPath: /var/cache/nginx/client_temp
            - name: nginx-cache-volume
              mountPath: /var/cache/nginx/proxy_temp
            - name: nginx-cache-volume
              mountPath: /var/cache/nginx/fastcgi_temp
            - name: nginx-cache-volume
              mountPath: /var/cache/nginx/uwsgi_temp
            - name: nginx-cache-volume
              mountPath: /var/cache/nginx/scgi_temp
            - name: nginx-run-volume # <-- YENİ EKLENEN PID DİZİNİ
              mountPath: /run
      volumes: # Bu volume'lar tüm yukarıdaki mount noktaları için kullanılacak
        - name: nginx-cache-volume
          emptyDir: {}
        - name: nginx-run-volume # <-- YENİ EKLENEN VOLUME TANIMI
          emptyDir: {}