apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app-prometheus-node-exporter
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
        app.kubernetes.io/component: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:v1.6.1
          ports:
            - containerPort: 9100
              name: metrics
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi