apiVersion: apps/v1
kind: StatefulSet
metadata:
  # DÜZELTME: İsim, _helpers.tpl dosyasındaki doğru tanımdan çağrılıyor.
  name: {{ include "my-app.fullname" . }}-mongodb
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  # DÜZELTME: Servis adı da doğru tanımdan çağrılıyor.
  serviceName: {{ include "my-app.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.service.port }}
              protocol: TCP
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}