---
- name: Helm ile Kubernetes Dağıtım ve Güvenlik Denetimi
  hosts: k3s_cluster
  become: true # Görevlerin root yetkisiyle çalışmasını sağlar (örn: dosya kopyalama)
  
  vars_files:
    # Ansible'ın çalıştığı dizine göre secrets.yaml dosyasının yolu
    - secrets/secrets.yaml

  vars:
    helm_release_name: "my-app"
    k8s_namespace: "default"
    frontend_image_repo: "meyfcsalik/frontend"
    frontend_image_tag: "latest"
    backend_image_repo: "meyfcsalik/backend"
    backend_image_tag: "latest"
    app_domain: "app.mustafasalik.de"
    enable_selenium_tests: true
    playbook_dir: "{{ lookup('env', 'PWD') }}/ansible" # Ansible dizininin mutlak yolu

  tasks:
    # --------------------------------------------------------------------------
    # GÖREV BLOKU 1: Kubeconfig Dosyasını K3s Master Üzerinde Ayarlama
    # --------------------------------------------------------------------------
    - name: Kubeconfig Dosyasını Ayarla ve Sunucu Adresini Güncelle
      block:
        - name: /home/{{ ansible_user }} dizininin var olduğundan emin ol
          ansible.builtin.file:
            path: /home/{{ ansible_user }}
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'

        - name: Kubeconfig dosyasını /etc/rancher/k3s/k3s.yaml'dan kopyala
          ansible.builtin.copy:
            src: /etc/rancher/k3s/k3s.yaml
            dest: /home/{{ ansible_user }}/kubeconfig
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0600' # Sadece sahip okuma/yazma iznine sahip olsun
            remote_src: yes # Kaynak dosyanın hedef makinede olduğunu belirtir

        - name: Kubeconfig sunucu adresini localhost'tan gerçek IP'ye güncelle
          ansible.builtin.replace:
            path: /home/{{ ansible_user }}/kubeconfig
            regexp: 'server: https:\/\/((127\.0\.0\.1)|(localhost)):6443'
            replace: 'server: https://{{ ansible_host }}:6443'

        - name: Kubeconfig dosya içeriğini doğrula (sunucu adresi)
          ansible.builtin.command: cat /home/{{ ansible_user }}/kubeconfig
          register: kubeconfig_content
          changed_when: false # Bu komut durumu değiştirmez

        - name: Doğrulama için kubeconfig sunucu adresini göster
          ansible.builtin.debug:
            msg: "Kubeconfig sunucu adresi: {{ kubeconfig_content.stdout | regex_search('server: (.*)', '\\1') | first }}"

      tags: kubeconfig_setup

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 2: Kubernetes Kaynakları
    # --------------------------------------------------------------------------
    - name: Selenium test betiği ConfigMap'ini oluştur
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/configs/selenium-test-configmap.yaml') | from_yaml }}"
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
      tags: configmap

    - name: Helm chart'ını dağıt veya güncelle
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ playbook_dir }}/../helm/my-app/" # Helm chart'ınızın yolu
        release_namespace: "{{ k8s_namespace }}"
        create_namespace: yes
        values:
          frontend:
            image:
              repository: "{{ frontend_image_repo }}"
              tag: "{{ frontend_image_tag }}"
          backend:
            image:
              repository: "{{ backend_image_repo }}"
              tag: "{{ backend_image_tag }}"
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
      tags: deploy

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 3: Güvenlik Politikaları
    # --------------------------------------------------------------------------
    - name: Pod Güvenlik Standartlarını uygula (Namespace'e etiket ekle)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"
            labels:
              pod-security.kubernetes.io/enforce: baseline
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
      tags: security

    - name: Gelişmiş NetworkPolicy tanımla
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-monitoring-only
            namespace: "{{ k8s_namespace }}"
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
            ingress:
              - ports:
                  - protocol: TCP
                    port: 9100
                from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: monitoring
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
      tags: security

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 4: Test ve Otomasyon
    # --------------------------------------------------------------------------
    - name: Selenium test Job'unu başlat
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "{{ helm_release_name }}-selenium-test-{{ lookup('pipe', 'date +%s') }}"
            namespace: "{{ k8s_namespace }}"
          spec:
            ttlSecondsAfterFinished: 300
            template:
              spec:
                containers:
                  - name: selenium-runner
                    image: python:3.9-slim
                    command: ["python3", "/app/run_tests.py"]
                    volumeMounts:
                      - name: test-scripts-volume
                        mountPath: /app
                volumes:
                  - name: test-scripts-volume
                    configMap:
                      name: selenium-test-script
                restartPolicy: Never
            backoffLimit: 0
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
        when: enable_selenium_tests
      tags: testing

    # - name: Vault şifresini otomatik döndür (İsteğe bağlı, dikkatli kullanın)
    #   ansible.builtin.command: >
    #     ansible-vault rekey secrets.yaml
    #     --new-vault-password-file {{ playbook_dir }}/vault_pass_new.txt
    #   args:
    #     creates: "{{ playbook_dir }}/vault_pass_new.txt"
    #   run_once: true
    #   tags: vault

  # ============================================================================
  # POST TASKS: Tüm ana görevler bittikten sonra çalışır
  # ============================================================================
  post_tasks:
    - name: Dağıtım sonrası Pod durumlarını kontrol et
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ k8s_namespace }}"
        label_selectors:
          - "app.kubernetes.io/instance={{ helm_release_name }}"
        kubeconfig: /home/{{ ansible_user }}/kubeconfig
      register: deployment_pods
      retries: 10
      delay: 5
      until: deployment_pods.resources | length > 0
      run_once: true

    - name: Uygulama sağlık durumunu kontrol et (Health Check)
      ansible.builtin.uri:
        url: "http://{{ item.metadata.name }}.{{ k8s_namespace }}.svc.cluster.local/health"
        method: GET
        status_code: 200
        timeout: 10
      loop: "{{ deployment_pods.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
      retries: 10
      delay: 5
      run_once: true