- name: Helm ile Kubernetes Dağıtım ve Güvenlik Denetimi
  hosts: k3s_cluster
  become: true

  vars_files:
    - secrets/secrets.yaml

  vars:
    helm_release_name: "my-app"
    k8s_namespace: "my-app-ns"
    frontend_image_repo: "meyfcsalik/frontend"
    frontend_image_tag: "latest"
    backend_image_repo: "meyfcsalik/backend"
    backend_image_tag: "latest"
    playbook_dir: "{{ lookup('env', 'PWD') }}/ansible"
    # DÜZELTME: Chart'ın yerel ve uzak yolları için ayrı değişkenler tanımlandı.
    local_helm_chart_path: "{{ playbook_dir }}/../helm/my-app"
    remote_helm_chart_path: "/tmp/{{ helm_release_name }}-chart"
    critical_paths_k3s:
      - /etc/rancher/k3s/
      - /var/lib/rancher/k3s/server/
      - /var/lib/kubelet

  pre_tasks:
    - name: Önceki dağıtımdan kalan geçici chart dizinini temizle
      ansible.builtin.file:
        path: "{{ remote_helm_chart_path }}"
        state: absent

  tasks:
    # --------------------------------------------------------------------------
    # GÖREV BLOKU 1: Kubeconfig Dosyasını Ayarlama
    # --------------------------------------------------------------------------
    - name: Kubeconfig Dosyasını Ayarla ve Sunucu Adresini Güncelle
      tags: kubeconfig_setup
      block:
        - name: Kullanıcı ev dizininin var olduğundan emin ol
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'

        - name: Kubeconfig dosyasını /etc/rancher/k3s/k3s.yaml'dan kopyala
          ansible.builtin.copy:
            src: /etc/rancher/k3s/k3s.yaml
            dest: "/home/{{ ansible_user }}/kubeconfig"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0600'
            remote_src: yes

        - name: Kubeconfig sunucu adresini localhost'tan gerçek IP'ye güncelle
          ansible.builtin.replace:
            path: "/home/{{ ansible_user }}/kubeconfig"
            regexp: 'server: https:\/\/((127\.0\.0\.1)|(localhost)):6443'
            replace: 'server: https://{{ ansible_host }}:6443'

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 2: Kubernetes Kaynakları (ConfigMap ve Helm Dağıtımı)
    # --------------------------------------------------------------------------
    - name: Selenium test betiği ConfigMap'ini oluştur
      tags: configmap
      kubernetes.core.k8s:
        state: present
        definition: "{{ (lookup('file', playbook_dir + '/configs/selenium-test-configmap.yaml') | from_yaml) | combine({'metadata': {'namespace': k8s_namespace}}, recursive=True) }}"
        kubeconfig: "/home/{{ ansible_user }}/kubeconfig"

    - name: Dağıtım yapılacak ad alanının var olduğundan emin ol
      tags: deploy
      kubernetes.core.k8s:
        name: "{{ k8s_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "/home/{{ ansible_user }}/kubeconfig"

    # YENİ GÖREV: Helm komutu uzak sunucuda çalışacağından, önce chart dosyalarını
    # yerel kontrolcüden uzak sunucuya kopyalamamız gerekiyor.
    - name: Helm chart dosyalarını uzak sunucuya kopyala
      tags: deploy
      ansible.builtin.copy:
        src: "{{ local_helm_chart_path }}/"
        dest: "{{ remote_helm_chart_path }}/"
        mode: '0755'

    - name: Helm chart'ını komut satırından dağıt veya güncelle
      tags: deploy
      ansible.builtin.shell:
        # DÜZELTME: Helm komutu, uzak sunucuya kopyalanan chart ve values dosyalarını
        # kullanacak şekilde güncellendi.
        cmd: >
          helm upgrade --install {{ helm_release_name }}
          {{ remote_helm_chart_path }}
          --namespace {{ k8s_namespace }}
          --values {{ remote_helm_chart_path }}/values.yaml
          --values {{ remote_helm_chart_path }}/values-{{ deploy_env_name }}.yaml
          --set frontend.image.repository={{ frontend_image_repo }}
          --set frontend.image.tag={{ frontend_image_tag }}
          --set backend.image.repository={{ backend_image_repo }}
          --set backend.image.tag={{ backend_image_tag }}
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/kubeconfig"
      register: helm_result
      changed_when: "'Release was upgraded' in helm_result.stdout or 'installed' in helm_result.stdout"

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 3: Güvenlik Denetimleri
    # --------------------------------------------------------------------------
    - name: Güvenlik denetimlerini çalıştır
      tags: security
      block:
        - name: Kritik K3s dizinlerinin varlığını doğrula
          ansible.builtin.stat:
            path: "{{ item }}"
          loop: "{{ critical_paths_k3s }}"
          register: k3s_dirs_check

        - name: Eksik kritik K3s dizinleri varsa uyar ve başarısız ol
          ansible.builtin.fail:
            msg: "GÜVENLİK RİSKİ: Kritik K3s dizini bulunamadı -> {{ item.item }}"
          loop: "{{ k3s_dirs_check.results }}"
          when: not item.stat.exists

        - name: Kritik dizinlerdeki herkese açık yazılabilir dosyaları bul
          ansible.builtin.command: "find {{ item }} -type f -perm /o=w"
          loop: "{{ critical_paths_k3s }}"
          register: insecure_files_check
          changed_when: false
          failed_when: insecure_files_check.rc > 1

        - name: Güvensiz dosya izinleri varsa uyar ve başarısız ol
          ansible.builtin.fail:
            msg: "GÜVENLİK AÇIĞI! {{ item.item }} yolunda güvensiz izinlere sahip dosya(lar) bulundu: {{ item.stdout_lines }}"
          loop: "{{ insecure_files_check.results }}"
          when:
            - item.stdout != ""
            - deploy_env_name == 'prod'

    # --------------------------------------------------------------------------
    # GÖREV BLOKU 4: Kubernetes Güvenlik ve Testler
    # --------------------------------------------------------------------------
    - name: Pod Güvenlik Standartlarını uygula
      tags: security
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"
            labels:
              pod-security.kubernetes.io/enforce: baseline
        kubeconfig: "/home/{{ ansible_user }}/kubeconfig"

    - name: Selenium test Job'unu başlat
      tags: testing
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "{{ helm_release_name }}-selenium-test-{{ lookup('pipe', 'date +%s') }}"
            namespace: "{{ k8s_namespace }}"
          spec:
            ttlSecondsAfterFinished: 300
            template:
              spec:
                containers:
                  - name: selenium-runner
                    image: python:3.9-slim
                    command: ["python3", "/app/run_tests.py"]
                    volumeMounts:
                      - name: test-scripts-volume
                        mountPath: /app
                volumes:
                  - name: test-scripts-volume
                    configMap:
                      name: selenium-test-script
                restartPolicy: Never
            backoffLimit: 0
        kubeconfig: "/home/{{ ansible_user }}/kubeconfig"
