# ===========================================================
# ==             ANA HELM DEĞERLERİ DOSYASI                ==
# ===========================================================

# Genel Uygulama ve Ortam Ayarları
# -----------------------------------------------------------
# 'namespace' anahtarı, chart'ın kendi ad alanını yönetmesi
# (örn: templates/namespace.yaml) için kullanılır.
namespace: default

# Hangi ortam için değerlerin ayarlandığını belirtir.
environment: production

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# ServiceAccount Ayarları
# -----------------------------------------------------------
serviceAccount:
  create: true
  annotations: {}
  name: "" # Otomatik isim için boş bırakın

# Pod Güvenlik Konteksti
# -----------------------------------------------------------
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1001

# Container Güvenlik Konteksti
# -----------------------------------------------------------
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1001

# ===========================================================
# ==                   BİLEŞEN AYARLARI                    ==
# ===========================================================

# Frontend Ayarları
# -----------------------------------------------------------
frontend:
  name: frontend
  # GÜNCELLEME: Üretim ortamı için replica sayısı 2'ye çıkarıldı.
  replicaCount: 2
  image:
    repository: meyfcsalik/frontend
    pullPolicy: IfNotPresent
    # CI/CD pipeline'ınız bu değeri (örneğin commit SHA ile) doldurmalıdır.
    tag: "production-latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10

# Backend Ayarları
# -----------------------------------------------------------
backend:
  name: backend
  # GÜNCELLEME: Üretim ortamı için replica sayısı 2'ye çıkarıldı.
  replicaCount: 2
  image:
    repository: meyfcsalik/backend
    pullPolicy: IfNotPresent
    tag: "production-latest"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  env:
    # GÜNCELLEME: Üretim veritabanı adresi kullanıldı.
    MONGO_URL: "mongodb://{{ include \"my-app.fullname\" . }}-mongodb:27017/my-app_production"
    # GÜNCELLEME: Ortam "production" olarak ayarlandı.
    NODE_ENV: "production"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 5

# MongoDB Ayarları
# -----------------------------------------------------------
mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: "6.0"
  service:
    name: "mongodb"
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    # GÜNCELLEME: Üretim ortamı için disk boyutu artırıldı.
    size: 10Gi

# Ingress Ayarları
# -----------------------------------------------------------
ingress:
  # GÜNCELLEME: Üretim ortamında dışarıya erişim için 'true' yapıldı.
  enabled: true
  className: nginx # Kullandığınız Ingress Controller'a göre değiştirin.
  hosts:
    - host: my-app.local # Burayı kendi domain adınızla değiştirin.
      paths:
        - path: /
          pathType: Prefix

# Monitoring (kube-prometheus-stack) Ayarları
# -----------------------------------------------------------
monitoring:
  # GÜNCELLEME: Üretim ortamında izleme aktif edildi.
  enabled: true
  kube-prometheus-stack:
    # DÜZELTME: PrometheusRule kaynağının hangi ad alanında oluşturulacağını
    # belirtmek için 'namespace' anahtarı eklendi. Bu, "nil pointer" hatasını çözer.
    namespace: monitoring
    grafana:
      # ÖNEMLİ: Bu şifre CI/CD üzerinden veya bir secret'tan güvenli bir şekilde sağlanmalıdır.
      adminPassword: "CHANGEME"