# ===========================================================
# ==             ANA HELM DEĞERLERİ DOSYASI                ==
# ===========================================================

# Genel Uygulama ve Ortam Ayarları
# -----------------------------------------------------------
# 'namespace' anahtarı, chart'ın kendi ad alanını yönetmesi
# (örn: templates/namespace.yaml) için kullanılır.
namespace: default

# Varsayılan ortam ayarı
environment: development

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# ServiceAccount Ayarları
# -----------------------------------------------------------
serviceAccount:
  create: true
  annotations: {}
  name: "" # Otomatik isim için boş bırakın

# Pod Güvenlik Konteksti
# -----------------------------------------------------------
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1001

# Container Güvenlik Konteksti
# -----------------------------------------------------------
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1001

# ===========================================================
# ==             VARSAYILAN BİLEŞEN AYARLARI               ==
# ===========================================================

# Frontend Ayarları
# -----------------------------------------------------------
frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: meyfcsalik/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10

# Backend Ayarları
# -----------------------------------------------------------
backend:
  name: backend
  replicaCount: 1
  image:
    repository: meyfcsalik/backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  env:
    MONGO_URL: "mongodb://{{ include \"my-app.fullname\" . }}-mongodb:27017/my-app_default"
    NODE_ENV: "development"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 5

# MongoDB Ayarları
# -----------------------------------------------------------
mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: "6.0"
  service:
    name: "mongodb"
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    size: 1Gi

# Ingress Ayarları
# -----------------------------------------------------------
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix

# Monitoring (kube-prometheus-stack) Ayarları
# -----------------------------------------------------------
monitoring:
  enabled: false
  kube-prometheus-stack:
    namespace: monitoring
    grafana:
      adminPassword: "CHANGEME"