# Ortam Adı
environment: production

frontend:
  replicaCount: 2
  image:
    tag: "production-latest"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

backend:
  replicaCount: 2
  image:
    tag: "production-latest"
  env:
    MONGO_URL: "mongodb://{{ include \"my-app.fullname\" . }}-mongodb:27017/my-app_production"
    NODE_ENV: "production"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mongodb:
  persistence:
    size: "10Gi"

ingress:
  enabled: true
  hosts:
    - host: prod.my-app.com # Domain adınızı güncelleyin
      paths:
        - path: /
          pathType: Prefix

monitoring:
  enabled: true
  kube-prometheus-stack:
    # DÜZELTME: 'namespace' anahtarı buraya da eklendi.
    namespace: monitoring
    prometheus:
      prometheusSpec:
        replicas: 2
        retention: "30d"
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
    grafana:
      adminPassword: "" # CI/CD'den güvenli bir şekilde sağlanmalı
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"