namespace: default
environment: development

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1001

frontend:
  enabled: true
  name: frontend
  replicaCount: 1
  image:
    repository: meyfcsalik/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10

backend:
  name: backend
  replicaCount: 1
  image:
    repository: meyfcsalik/backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  env:
    MONGO_URL: "mongodb://{{ include \"my-app.fullname\" . }}-mongodb:27017/my-app_default"
    NODE_ENV: "development"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 5

mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: "6.0"
  service:
    name: "mongodb"
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    size: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app.mustafasalik.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-app-frontend
              port:
                number: 80
  tls: []

monitoring:
  enabled: true
  kube_prometheus_stack:
    namespace: "monitoring"
    grafana:
      adminPassword: "CHANGEME"