# Ortam Adı
environment: staging

frontend:
  replicaCount: 1
  image:
    tag: "staging-latest"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

backend:
  replicaCount: 1
  image:
    tag: "staging-latest"
  env:
    MONGO_URL: "mongodb://{{ include \"my-app.fullname\" . }}-mongodb:27017/my-app_staging"
    NODE_ENV: "staging"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

mongodb:
  persistence:
    size: "2Gi"

ingress:
  enabled: true
  hosts:
    - host: staging.my-app.com # Domain adınızı güncelleyin
      paths:
        - path: /
          pathType: Prefix

monitoring:
  enabled: true
  kube-prometheus-stack:
    # DÜZELTME: 'namespace' anahtarı buraya da eklendi.
    namespace: monitoring
    prometheus:
      prometheusSpec:
        replicas: 1
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
    grafana:
      adminPassword: "" # CI/CD'den güvenli bir şekilde sağlanmalı
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"