# values-staging.yaml - Staging Ortamı İçin Değerler

frontend:
  replicaCount: 1
  image:
    repository: yourdockerhubusername/frontend # KENDİ DOCKER HUB KULLANICI ADINLA DEĞİŞTİR
    # tag: "staging-latest" # CI/CD tarafından dinamik olarak set edilecek
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

backend:
  replicaCount: 1
  image:
    repository: yourdockerhubusername/backend # KENDİ DOCKER HUB KULLANICI ADINLA DEĞİŞTİR
    # tag: "staging-latest" # CI/CD tarafından dinamik olarak set edilecek
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  env:
    MONGO_URL: "mongodb://myapp-mongodb:27017/myappdb_staging" # Staging DB adı

mongodb:
  replicaCount: 1
  persistence:
    size: 1Gi # Staging için daha küçük disk boyutu
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
